spring.application.name=foodwaste

spring.datasource.url=jdbc:postgresql://localhost:5432/food_waste_db
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect

app.jwt.secret=q8JjK9zFhT1z7vXkY2p3s9QwR1u5v6z8n0aBcDeFgHiJkLmNoPqRsTuVwXyZ1234==
app.jwt.expiration-ms=86400000

# docker run --name foodwaste-postgres -e POSTGRES_USER=postgres  -e POSTGRES_PASSWORD=0000 -e POSTGRES_DB=food_waste_db  -p 5432:5432 -d postgres:latest